---

- name: Brew cask Software
  homebrew_cask:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - flux
      - avibrazil-rdm
      - discord
      - slack
      - alfred
      - firefox
      - github
      - 1password
