---

- name: brew cask software
  homebrew_cask:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - flux
      - alfred
      - github
      - postman
      - insomnia
      - whatsapp
      - telegram
      - 1password
      - fantastical
      - iterm2
      - notion
      - google-chrome
      - firefox
      - avibrazil-rdm
      - datagrip
      - visual-studio-code
      - monitorcontrol
      - docker
