---

- name: Brew cask Software
  homebrew_cask:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - flux
      - alfred
      - github
      - postman
      - 1password
      - fantastical
      - iterm2
