---

- homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- homebrew_tap:
    name: sambadevi/powerlevel9k
    state: present

- name: Brew packages
  homebrew:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
     - stow
     - tmux
     - ranger
     - powerlevel9k
     - node

- name: Brew cask packages
  homebrew_cask:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
     - font-hack-nerd-font

- name: Check if ohmyzsh is installed
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh

- name: Install ohmyzsh
  when: not ohmyzsh.stat.exists
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh

- name: Node packages
  npm:
    name: "{{ packages }}"
    global: yes
  vars:
    packages:
      - neovim
      - typescript
      - typescript-language-server
      - vscode-langservers-extracted

- name: Python packages
  pip:
    name:
      - neovim
