require('plugins')
require('settings')
require('lsp')
require('binds')
require('plugins/treesitter-config')
require('plugins/telescope-config')
require('plugins/nvim-cmp-config')
require('plugins/formatter-config')
